site_name: List Formatting Samples
nav:
  - Home: 'index.md'
theme:
  name: 'material'
  palette:
    primary: 'teal'
  logo: 'img/Logo.png'
  feature:
    tabs: true
extra_css:
  - 'css/extra.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
plugins:
  - search
  - markdownextradata
extra:
  version: '1.3.2-0'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/officedevpnp'
    - type: 'youtube'
      link: 'https://www.youtube.com/playlist?list=PLR9nK3mnD-OXgMjDBdjWUTRia89oixBhx'
    - type: 'link'
      link: 'https://aka.ms/sppnp'
repo_url: https://github.com/SharePoint/sp-dev-list-formatting
edit_uri: tree/master/docs
site_url: https://sharepoint.github.io/sp-dev-list-formatting/